[package]
name = "ipc_example"
version = "0.1.0"
authors = ["ZachsPage <xhmf1423@gmail.com>"]
edition = "2018"
default-run = "ipc_example"

[dependencies]
ipc_comms = { path = "./src/ipc_comms/" }
ipc-channel = "0.15.0"
