[package]
name = "ipc_comms"
version = "0.1.0"
authors = ["ZachsPage <xhmf1423@gmail.com>"]
edition = "2018"

[dependencies]
args = "2.0"
getopts = "0.2.21"
serde = { version = "1.0", features = ["derive"] }
ipc-channel = "0.15.0"
